version: '3'

services:
  # app:
  #   #image: ghcr.io/melvinidema/jubilant-octo-bassoon:main
  #   build: .
  #   ports:
  #     - "6969:6969"
  #   restart: unless-stopped
  #   volumes:
  #     - "./.env:/app/.env"
  #   depends_on:
  #     - db
  db:
    image: mysql:8.0-debian
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: poems
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db